--- # Infrastructure demo YAML - install httpd on redhat
- hosts: "{{ hosts_group }}"
  remote_user: "{{ initial_user }}"
  become: yes
  become_method: sudo
  connection: ssh
  gather_facts: no
  vars:
    hosts_group: mclab
    initial_user: mc
  tasks:
  - name: Check if group 'wheel' exist
    group:
      name: wheel
      state: present
  - name: Allow 'wheel' group to have passwordless abilities
    lineinfile:
      dest: /etc/sudoers
      state: present
      regexp: '^%wheel'
      line: '%wheel ALL=(ALL) NOPASSWD: ALL'
      validate: visudo -cf %s 
  - name: Add user ansible with sudo privileges 
    user:
      name: ansible
      groups: wheel
      append: yes
      state: present
  - name: Set up authorized keys for ansible user
    authorized_key:
      user: ansible
      state: present      
      key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"
